theme: minima

title: Numérique & Ministères de l'Écologie et des Territoires

header_pages:
  - dataroom.md
  - fabrique-numerique/index.md
  - geek-lunch/index.md
  - ressources/index.md

collections:
  startup:
    output: true
    permalink: /startup/:title.html

defaults:
  -
    scope:
      path: ""
      type: "startup"
    values:
      layout: "page"